version: "3"
services:
  mongoDb:
      container_name: "chat-v2-mongo"
      image: "mongo"
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_DATABASE: db

  server:
    build: server/
    ports:
      - "4000:4000"
    depends_on:
      - mongoDb

  client:
    build: client/
    ports:
      - "3000:3000"


